# 베이스 라인 코드 실습

In [2]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

## CountVectorizer 클래스
    - 카운트 기반의 벡터화를 구현한 클래스로 피처 벡터화 뿐만 아니라, 소문자 일괄 변환, 토큰화, 스톱워드 필터링 등의 텍스트 전처리에 유용한 클래스


In [20]:
train = pd.read_csv("./open/sample_train.csv")
train.head(5)

code1  \
0  flag = "go"\ncnt = 0\nwhile flag == "go":\n   ...   
1   b, c = map(int, input().split())\n\nprint(b * c)   
2  import numpy as np\nimport sys\nread = sys.std...   
3   b, c = map(int, input().split())\n\nprint(b * c)   
4  s=input()\nt=input()\nans=0\nfor i in range(le...   

                                               code2  similar  
0  # Python 3+\n#--------------------------------...        1  
1  import numpy as np\n\nn = int(input())\na = np...        0  
2  N, M = map(int, input().split())\nif M%2 != 0:...        0  
3  n,m=map(int,input().split())\nh=list(map(int,i...        0  
4  import math\na,b,h,m=map(int,input().split())\...        0

In [5]:
test = pd.read_csv("./open/test.csv")
test.head(5)

pair_id                                              code1  \
0        1  def main():\n  s = input()\n  if s.count('a') ...   
1        2  N,K,Q = map(int,input().split())\npoints = [0]...   
2        3  from itertools import combinations\nn = int(in...   
3        4  a,b=map(int,input().split())\n\nans1=a+b\nans2...   
4        5  S = input()\nK = int(input())\n\nind = -1\nfor...   

                                               code2  
0  N,K = map(int,input().split())\nA = list(map(i...  
1  N, K, Q = map(int,input().split())\n\nif K > Q...  
2  s = input()\nt = input()\nlength_s = len(s)\nl...  
3  a, b, c, d = map(int,input().split())\n\nif a ...  
4  H, W = map(int, input().split())\ngrid = []\nf...

In [120]:
model = CountVectorizer()

In [122]:
model.fit(train['code1'])
model.fit(train['code2'])

CountVectorizer()

In [124]:
#model.vocabulary_

In [126]:
#model.get_feature_names_out()

In [69]:
m1 = CountVectorizer()

In [80]:
m1.fit_transform(train['code1'])
m1.fit_transform(train['code2'])

<17970x19033 sparse matrix of type '<class 'numpy.int64'>'
	with 329152 stored elements in Compressed Sparse Row format>

In [82]:
#m1.vocabulary_

## 테스트 벡터화

In [27]:
code1_vecs = model.transform(test['code1'])
code2_vecs = model.transform(test['code2'])

In [127]:
from sklearn.metrics.pairwise import cosine_similarity

In [159]:
code1_vecs

<179700x19033 sparse matrix of type '<class 'numpy.int64'>'
	with 3265320 stored elements in Compressed Sparse Row format>

In [138]:
preds = []
for code1_vec, code2_vec in zip(code1_vecs, code2_vecs):
    preds.append(cosine_similarity(code1_vec, code2_vec))

In [158]:
#preds
#len(preds)

In [148]:
preds_result = np.reshape(preds, len(preds))

In [152]:
preds_result

array([0.13363062, 0.83402338, 0.23569157, ..., 0.26375219, 0.83777494,
       0.45834925])

179700

In [38]:
type(preds_result)
#type(preds)

len(preds_result)
preds_result

array([0.13363062, 0.83402338, 0.23569157, ..., 0.26375219, 0.83777494,
       0.45834925])

In [163]:
preds_result[1] > 0.5 

True

In [153]:
final = np.where(preds_result > 0.5, 1, 0)

In [157]:
final

array([0, 1, 0, ..., 0, 1, 0])

In [43]:
corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
    'The last document?',
]

In [44]:
vect = CountVectorizer()

In [46]:
# corpus 리스트 내부 텍스트로 부터 각 단어의 빈도 수를 기록합니다.
print(vect.fit_transform(corpus).toarray()) 

[[0 1 1 1 0 0 0 1 0 1]
 [0 1 0 1 0 0 2 1 0 1]
 [1 0 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 0 1 0 1]
 [0 1 0 0 1 0 0 1 0 0]]


In [47]:
# 각 단어의 인덱스가 어떻게 부여되었는지를 보여줍니다.
print(vect.vocabulary_)

{'this': 9, 'is': 3, 'the': 7, 'first': 2, 'document': 1, 'second': 6, 'and': 0, 'third': 8, 'one': 5, 'last': 4}


In [60]:
vect.get_feature_names_out()

array(['and', 'document', 'first', 'is', 'last', 'one', 'second', 'the',
       'third', 'this'], dtype=object)

In [65]:
from sklearn.model_selection import train_test_split